/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package cc.grepon.relais

import org.json.JSONArray
import org.json.JSONObject
import org.json.JSONTokener

/**
 * Pure (no Android/Context) logic for OpenAI `response_format` structured output.
 *
 * Engine strategy (see docs/litertlm-native-api.md): `json_schema` is generated by advertising the
 * caller's schema as a single native tool (the model emits clean schema-conforming JSON as the tool
 * call's arguments — verified on-device); those arguments become the response content. `json_object`
 * uses a prompt nudge. BOTH are gated here by validation + repair + bounded retry, because
 * `enableConversationConstrainedDecoding` is NOT a hard grammar guarantee in litertlm 0.11.0.
 */
object RelaisStructuredOutput {

  /** Parsed `response_format` field. */
  sealed interface ResponseFormat {
    data object Text : ResponseFormat
    data object JsonObject : ResponseFormat
    data class JsonSchema(val name: String, val schema: JSONObject, val strict: Boolean) : ResponseFormat
  }

  /**
   * Parses `body.response_format`.
   *  - absent / null / `{"type":"text"}`            -> [ResponseFormat.Text]
   *  - `{"type":"json_object"}`                      -> [ResponseFormat.JsonObject]
   *  - `{"type":"json_schema","json_schema":{...}}`  -> [ResponseFormat.JsonSchema]
   *  - unknown non-null `type`, or a non-object value -> null (caller should answer HTTP 400)
   */
  fun parseResponseFormat(body: JSONObject): ResponseFormat? {
    if (!body.has("response_format") || body.isNull("response_format")) return ResponseFormat.Text
    val rf = body.opt("response_format") as? JSONObject ?: return null
    return when (rf.optString("type", "text")) {
      "text" -> ResponseFormat.Text
      "json_object" -> ResponseFormat.JsonObject
      "json_schema" -> {
        val js = rf.optJSONObject("json_schema") ?: JSONObject()
        ResponseFormat.JsonSchema(
          name = js.optString("name", "response").ifBlank { "response" },
          schema = js.optJSONObject("schema") ?: JSONObject(),
          strict = js.optBoolean("strict", false),
        )
      }
      else -> null
    }
  }

  /** OpenAI `function` object string for the native [OpenApiTool] bridge (feature-04). */
  fun schemaToFunctionJson(name: String, schema: JSONObject): String =
    JSONObject()
      .put("name", name)
      .put("description", "Return ONLY the structured result conforming to the schema.")
      .put("parameters", schema)
      .toString()

  /**
   * True iff [candidate] satisfies [format]:
   *  - [ResponseFormat.Text]       -> always (no constraint).
   *  - [ResponseFormat.JsonObject] -> parses as a JSON object.
   *  - [ResponseFormat.JsonSchema] -> parses as JSON and satisfies the (minimal) schema.
   */
  fun isValidOutput(candidate: String, format: ResponseFormat): Boolean =
    when (format) {
      is ResponseFormat.Text -> true
      is ResponseFormat.JsonObject -> parseJsonObjectOrNull(candidate) != null
      is ResponseFormat.JsonSchema -> validateSchema(candidate, format.schema)
    }

  /**
   * Extracts a balanced top-level JSON object/array from prose or ```json fences. Considers every
   * `{`/`[` start position and returns the **largest** fragment that parses as JSON — so a stray
   * decoy token (e.g. `Here is item [1]: {...}`) doesn't hijack extraction. Null when unsalvageable.
   */
  fun repairOutput(candidate: String): String? {
    val stripped = candidate
      .replace(Regex("```[a-zA-Z]*"), "")
      .replace("```", "")
    var best: String? = null
    for (i in stripped.indices) {
      val open = stripped[i]
      if (open != '{' && open != '[') continue
      val frag = balancedFrom(stripped, i, open) ?: continue
      if (!parsesAsJson(frag)) continue
      val b = best
      if (b == null || frag.length > b.length) best = frag
    }
    return best
  }

  /** The balanced `open…close` substring starting at [start] (respecting strings/escapes), or null. */
  private fun balancedFrom(s: String, start: Int, open: Char): String? {
    val close = if (open == '{') '}' else ']'
    var depth = 0
    var inStr = false
    var escaped = false
    for (i in start until s.length) {
      val c = s[i]
      if (inStr) {
        when {
          escaped -> escaped = false
          c == '\\' -> escaped = true
          c == '"' -> inStr = false
        }
        continue
      }
      when (c) {
        '"' -> inStr = true
        open -> depth++
        close -> {
          depth--
          if (depth == 0) return s.substring(start, i + 1).trim()
        }
      }
    }
    return null
  }

  /** Retry iff attempts remain AND a valid repair hasn't already been found. */
  fun shouldRetry(attempts: Int, maxRetries: Int, repaired: String?, format: ResponseFormat): Boolean =
    attempts < maxRetries && !(repaired != null && isValidOutput(repaired, format))

  // --- internals ---

  private fun parseJsonObjectOrNull(s: String): JSONObject? = runCatching { JSONObject(s) }.getOrNull()

  private fun parsesAsJson(s: String): Boolean =
    runCatching {
      val v = JSONTokener(s).nextValue()
      v is JSONObject || v is JSONArray
    }.getOrDefault(false)

  /** Minimal JSON-Schema check: top-level type, required, properties (1 level), additionalProperties:false. */
  private fun validateSchema(candidate: String, schema: JSONObject): Boolean {
    val value = runCatching { JSONTokener(candidate).nextValue() }.getOrNull() ?: return false
    return when (schema.optString("type", "object")) {
      "object" -> validateObject(value, schema)
      "array" -> value is JSONArray
      "string" -> value is String
      "boolean" -> value is Boolean
      "integer", "number" -> isJsonNumber(value)
      "null" -> value == JSONObject.NULL
      else -> value is JSONObject || value is JSONArray // unknown type: accept any JSON
    }
  }

  private fun validateObject(value: Any?, schema: JSONObject): Boolean {
    if (value !is JSONObject) return false
    val properties = schema.optJSONObject("properties")
    // required: every listed key must be present
    schema.optJSONArray("required")?.let { req ->
      for (i in 0 until req.length()) if (!value.has(req.optString(i))) return false
    }
    // additionalProperties:false -> no keys outside properties
    if (!schema.optBoolean("additionalProperties", true)) {
      val allowed = properties?.keys()?.asSequence()?.toSet() ?: emptySet()
      for (k in value.keys()) if (k !in allowed) return false
    }
    // per-property type (one level deep)
    if (properties != null) {
      for (k in properties.keys()) {
        if (!value.has(k)) continue
        val propType = properties.optJSONObject(k)?.optString("type") ?: continue
        if (propType.isBlank()) continue
        if (!matchesType(value.get(k), propType)) return false
      }
    }
    return true
  }

  private fun matchesType(v: Any?, type: String): Boolean =
    when (type) {
      "string" -> v is String
      "boolean" -> v is Boolean
      "integer", "number" -> isJsonNumber(v) // lenient: the engine returns floats (42.0) for integers
      "object" -> v is JSONObject
      "array" -> v is JSONArray
      "null" -> v == JSONObject.NULL
      else -> true
    }

  // org.json may parse numbers as Integer/Long/Double/BigDecimal/BigInteger; Boolean is NOT a number.
  private fun isJsonNumber(v: Any?): Boolean = v is Number
}
